name: Open Daily Issue
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Get Date
        run: echo "NOW=$(date +'%A, %e %B')" >> $GITHUB_ENV
      - name: Open Issue
        run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Daily Issue: ${{ env.NOW }}" --body "Hello World"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

