name: Merge test to QA
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test-qa:
    permissions:
      pull-requests: write
    # The 'uses' attribute must be changed to reflect the repo
    uses: j0hax/issues-test/.github/workflows/auto-pr.yml@main
    with:
      src-branch: test
      dst-branch: QA
