name: Open Weekly Issue
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  weekly-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Get Date
        run: echo "NOW=$(date +'Week Number %U')" >> $GITHUB_ENV
      - name: Open Issue
        run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Weekly Issue for ${{ env.NOW }}" --body "Hello World" --assignee j0hax
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
